### ISSUE TITLE
Performance issue.

### ISSUE THREAD

**Issue by akalverboer** [dstein64/k-means-quantization-js#1]
My experience is that you can make your  program much faster if you do not use the .slice method for defining a pixel.
So replace (in your program two times):
    arr.slice(i, i + n_channels) by [ arr[i+0], arr[i+1], arr[i+2], arr[i+4] ]
(if n_channels == 4)
It is a bit annoying to implement it for a general number of n_channels.

**Comment by dstein64** [comment]
Hi @akalverboer,

Thanks for letting me know about this optimization.

I have implemented a similar approach in a9889bf6c2593bfb2ea8d2188bd0deeac7efaabd, based on your suggestion. The approach supports an arbitrary number of channels.

This reduces the run time by about 75% for the large image I tested on (16 million pixels).

The run time was not affected notably for the small image I tested on (600,000 pixels).

I only switched away from using slice in one out of the two times it was used. When it's used outside the k-means algorithm (for constructing the initial dataset), there was not a meaningful impact on performance. Since the slice approach is more readable, I left that.
